export const MENU = [
  {
    title: "Mac",
    subMenu: [
      { title: "이 Mac에 관하여", valid: true },
      { title: "br" },
      { title: "시스템 설정", valid: true },
      { title: "App Store...", valid: true },
      { title: "br" },
      { title: "최근 사용 항목", valid: true },
      { title: "br" },
      { title: "강제종료", valid: true },
      { title: "br" },
      { title: "잠자기", valid: true },
      { title: "재시동", valid: true },
      { title: "br" },
      { title: "시스템 종료", valid: true },
      { title: "화면 잠금", valid: true },
      { title: "로그아웃", valid: true },
    ],
  },
  {
    title: "Finder",
    subMenu: [
      { title: "Finder에 관하여", valid: true },
      { title: "br" },
      { title: "설정...", valid: true },
      { title: "br" },
      { title: "휴지통 비우기", valid: true },
      { title: "br" },
      { title: "서비스", valid: true },
      { title: "br" },
      { title: "Finder 가리기", valid: true },
      { title: "기타 가리기", valid: true },
      { title: "모두보기", valid: false },
    ],
  },
  {
    title: "파일",
    subMenu: [
      { title: "새로운 Finder 윈도우", valid: true },
      { title: "새로운 폴더", valid: true },
      { title: "선택 항목을 포함하는 새로운 폴더", valid: false },
      { title: "새로운 스마트 폴더", valid: true },
      { title: "새로운 탭", valid: true },
      { title: "열기", valid: false },
      { title: "다음으로 열기", valid: false },
      { title: "윈도우 닫기", valid: false },
      { title: "모두 닫기", valid: true },
      { title: "br" },
      { title: "정보 가져오기", valid: true },
      { title: "이름 변경", valid: false },
      { title: "압축", valid: false },
      { title: "복제", valid: false },
      { title: "가상본 만들기", valid: false },
      { title: "훑어보기", valid: false },
      { title: "프린트", valid: false },
      { title: "br" },
      { title: "공유...", valid: false },
      { title: "br" },
      { title: "원본 보기", valid: false },
      { title: "Dock에 추가", valid: false },
      { title: "휴지통으로 이동", valid: false },
      { title: "추출", valid: false },
      { title: "br" },
      { title: "태그...", valid: false },
      { title: "br" },
      { title: "찾기", valid: true },
    ],
  },
  {
    title: "편집",
    subMenu: [
      { title: "실행 취소", valid: false },
      { title: "실행 복귀", valid: false },
      { title: "br" },
      { title: "오려두기", valid: false },
      { title: "복사", valid: false },
      { title: "붙여넣기", valid: false },
      { title: "전체 선택", valid: true },
      { title: "br" },
      { title: "클립보드 보기", valid: true },
      { title: "br" },
      { title: "받아쓰기 시작...", valid: true },
      { title: "이모티콘 및 기호", valid: true },
    ],
  },
  {
    title: "보기",
    subMenu: [
      { title: "아이콘", valid: false },
      { title: "목록", valid: false },
      { title: "계층", valid: false },
      { title: "갤러리", valid: false },
      { title: "br" },
      { title: "스택 사용", valid: true },
      { title: "다음으로 정렬", valid: true },
      { title: "선택항목 정리", valid: true },
      { title: "아이콘 정리 방식", valid: true },
      { title: "br" },
      { title: "사이드바 가리기", valid: false },
      { title: "미리보기 가리기", valid: false },
      { title: "br" },
      { title: "도구 막대 가리기", valid: false },
      { title: "모든 탭 보기", valid: false },
      { title: "탭 막대 가리기", valid: false },
      { title: "경로 막대 가리기", valid: false },
      { title: "상태 막대 가리기", valid: false },
      { title: "br" },
      { title: "도구 막대 사용자화...", valid: false },
      { title: "br" },
      { title: "보기 옵션", valid: true },
      { title: "미리보기 옵션 표시", valid: false },
      { title: "br" },
      { title: "전체 화면 시작", valid: false },
    ],
  },
  {
    title: "이동",
    subMenu: [
      { title: "뒤로", valid: false },
      { title: "앞으로", valid: false },
      { title: "상위폴더", valid: false },
      { title: "br" },
      { title: "최근 사용", valid: true },
      { title: "문서", valid: true },
      { title: "데스크탑", valid: true },
      { title: "다운로드", valid: true },
      { title: "홈", valid: true },
      { title: "컴퓨터", valid: true },
      { title: "AirDrop", valid: true },
      { title: "네트워크", valid: true },
      { title: "iCloud Drive", valid: true },
      { title: "공유", valid: true },
      { title: "응용 프로그램", valid: true },
      { title: "유틸리티", valid: true },
      { title: "br" },
      { title: "최근 사용 폴더", valid: true },
      { title: "br" },
      { title: "폴더로 이동...", valid: true },
      { title: "서버에 연결...", valid: true },
    ],
  },
  {
    title: "윈도우",
    subMenu: [
      { title: "최소화", valid: false },
      { title: "확대/축소", valid: false },
      { title: "화면 왼쪽으로 윈도우 이동", valid: false },
      { title: "화면 오른쪽으로 윈도우 이동", valid: false },
      { title: "배치된 윈도우 대치", valid: false },
      { title: "br" },
      { title: "세트에서 윈도우 제거", valid: false },
      { title: "윈도우 순환", valid: true },
      { title: "진행 윈도우 보기", valid: false },
      { title: "br" },
      { title: "이전 탭 보기", valid: false },
      { title: "다음 탭 보기", valid: false },
      { title: "새로운 윈도우로 탭 이동", valid: false },
      { title: "모든 윈도우 통합", valid: false },
      { title: "br" },
      { title: "모두 앞으로 가져오기", valid: true },
    ],
  },
  {
    title: "도움말",
    subMenu: [
      { title: "Mac을 위한 팁", valid: true },
      { title: "macOS 도움말", valid: true },
    ],
  },
] as const;

export const CONTEXT_MENU = [
  { title: "새로운 폴더", valid: true },
  { title: "br" },
  { title: "정보 가져오기", valid: true },
  { title: "배경화면 변경...", valid: true },
  { title: "br" },
  { title: "스택 사용", valid: true },
  { title: "다음으로 정렬", valid: true },
  { title: "아이콘 정리", valid: true },
  { title: "아이콘 정리 방식", valid: true },
  { title: "보기 옵션", valid: true },
  { title: "br" },
  { title: "iPhone에서 가져오기", valid: true },
] as const;

export const DATE_FORMAT = "M월 D일 (ddd) A h:mm" as const;
export const DATE_LOCALE = "ko" as const;
